
Welcome to Sopel. Loading modules...


Downloading malwaredomains db...
Error loading ipython: No module named IPython (modules/ipython.py:23)


Registered 40 modules,
1 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
WARNING:sopel.modules.ip:Downloading GeoIP database
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Warning: Couldn't load any modules
Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Warning: Couldn't load any modules
Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Warning: Couldn't load any modules
Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Warning: Couldn't load any modules
Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 1 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 1 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 1 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
CRITICAL:sopel.modules.coretasks:Nick changed by server. This can cause unexpected behavior. Please restart the bot.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 1 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 1 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
Traceback (most recent call last):
  File "/home/paul/workspace/sopel/sopenv/lib/python2.7/site-packages/sopel/bot.py", line 465, in call
    exit_code = func(sopel, trigger)
  File "/home/paul/.sopel/modules/vtbash.py", line 6, in vtbash
    bot.say(args)
  File "/home/paul/workspace/sopel/sopenv/lib/python2.7/site-packages/sopel/bot.py", line 402, in say
    self._bot.say(message, destination, max_messages)
  File "/home/paul/workspace/sopel/sopenv/lib/python2.7/site-packages/sopel/bot.py", line 300, in say
    text = encoded_text.decode('utf-8')
AttributeError: 'list' object has no attribute 'decode'

ERROR:sopel.modules.sopel.irc:Exception from #pew: AttributeError: 'list' object has no attribute 'decode' (file "/home/paul/workspace/sopel/sopenv/lib/python2.7/site-packages/sopel/bot.py", line 300, in say) (:pew!~pew@00020d55.user.oftc.net PRIVMSG #pew :.vtbash 2 4 5 3)
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 1 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 1 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 1 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 1 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 1 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading log: invalid syntax (log.py, line 16) (loader.py:197)


Registered 1 modules,
1 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading log: invalid syntax (log.py, line 16) (loader.py:197)


Registered 1 modules,
1 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error in log setup procedure: global name 'ChanlogsSection' is not defined (../../../../../../../.sopel/modules/log.py:5)


Registered 1 modules,
1 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading log: name 'FilenameAttribute' is not defined (../../../../../../../.sopel/modules/log.py:9)


Registered 1 modules,
1 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error in log setup procedure: global name 'threading' is not defined (../../../../../../../.sopel/modules/log.py:15)


Registered 1 modules,
1 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 2 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
Traceback (most recent call last):
  File "/home/paul/workspace/sopel/sopenv/lib/python2.7/site-packages/sopel/bot.py", line 465, in call
    exit_code = func(sopel, trigger)
  File "/home/paul/.sopel/modules/log.py", line 23, in log_everything
    with bot.memory['chanlog_locks'][fpath]:
KeyError: u'chanlog_locks'

ERROR:sopel.modules.sopel.irc:Exception from #pew: KeyError: u'chanlog_locks' (file "/home/paul/.sopel/modules/log.py", line 23, in log_everything) (:pew!~pew@00020d55.user.oftc.net PRIVMSG #pew :hello)
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 2 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
Traceback (most recent call last):
  File "/home/paul/workspace/sopel/sopenv/lib/python2.7/site-packages/sopel/bot.py", line 465, in call
    exit_code = func(sopel, trigger)
  File "/home/paul/.sopel/modules/log.py", line 23, in log_everything
    with bot.memory['chanlog_locks'][fpath]:
KeyError: u'chanlog_locks'

ERROR:sopel.modules.sopel.irc:Exception from #pew: KeyError: u'chanlog_locks' (file "/home/paul/.sopel/modules/log.py", line 23, in log_everything) (:pew!~pew@00020d55.user.oftc.net PRIVMSG #pew :hello)
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 2 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 2 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
Traceback (most recent call last):
  File "/home/paul/workspace/sopel/sopenv/lib/python2.7/site-packages/sopel/bot.py", line 465, in call
    exit_code = func(sopel, trigger)
  File "/home/paul/.sopel/modules/log.py", line 23, in log_everything
    with bot.memory['chanlog_locks'][fpath]:
KeyError: u'chanlog_locks'

ERROR:sopel.modules.sopel.irc:Exception from #pew: KeyError: u'chanlog_locks' (file "/home/paul/.sopel/modules/log.py", line 23, in log_everything) (:pew!~pew@00020d55.user.oftc.net PRIVMSG #pew :hello)
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 2 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
Traceback (most recent call last):
  File "/home/paul/workspace/sopel/sopenv/lib/python2.7/site-packages/sopel/bot.py", line 465, in call
    exit_code = func(sopel, trigger)
  File "/home/paul/.sopel/modules/log.py", line 23, in log_everything
    with [fpath]:
AttributeError: __exit__

ERROR:sopel.modules.sopel.irc:Exception from #pew: AttributeError: __exit__ (file "/home/paul/.sopel/modules/log.py", line 23, in log_everything) (:pew!~pew@00020d55.user.oftc.net PRIVMSG #pew :hello)
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 2 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
Traceback (most recent call last):
  File "/home/paul/workspace/sopel/sopenv/lib/python2.7/site-packages/sopel/bot.py", line 465, in call
    exit_code = func(sopel, trigger)
  File "/home/paul/.sopel/modules/log.py", line 24, in log_everything
    with bot.memory['chanlog_locks'][fpath]:
KeyError: u'chanlog_locks'

ERROR:sopel.modules.sopel.irc:Exception from #pew: KeyError: u'chanlog_locks' (file "/home/paul/.sopel/modules/log.py", line 24, in log_everything) (:pew!~pew@00020d55.user.oftc.net PRIVMSG #pew :hello)
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 2 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
Traceback (most recent call last):
  File "/home/paul/workspace/sopel/sopenv/lib/python2.7/site-packages/sopel/bot.py", line 465, in call
    exit_code = func(sopel, trigger)
  File "/home/paul/.sopel/modules/log.py", line 24, in log_everything
    with bot.memory['chanlog_locks'][fpath]:
KeyError: u'chanlog_locks'

ERROR:sopel.modules.sopel.irc:Exception from #pew: KeyError: u'chanlog_locks' (file "/home/paul/.sopel/modules/log.py", line 24, in log_everything) (:pew!~pew@00020d55.user.oftc.net PRIVMSG #pew :hello)
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading log: unexpected indent (log.py, line 25) (loader.py:197)


Registered 1 modules,
1 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 2 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 2 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 2 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
Traceback (most recent call last):
  File "/home/paul/workspace/sopel/sopenv/lib/python2.7/site-packages/sopel/bot.py", line 465, in call
    exit_code = func(sopel, trigger)
  File "/home/paul/.sopel/modules/log.py", line 22, in log_everything
    message = ''.join([datetime.utcnow(), trigger.nick, trigger, "\n"])
NameError: global name 'datetime' is not defined

ERROR:sopel.modules.sopel.irc:Exception from #pew: NameError: global name 'datetime' is not defined (file "/home/paul/.sopel/modules/log.py", line 22, in log_everything) (:pew!~pew@00020d55.user.oftc.net PRIVMSG #pew :.vtbash lksjdlk)
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 2 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
Traceback (most recent call last):
  File "/home/paul/workspace/sopel/sopenv/lib/python2.7/site-packages/sopel/bot.py", line 465, in call
    exit_code = func(sopel, trigger)
  File "/home/paul/.sopel/modules/log.py", line 23, in log_everything
    message = ''.join([datetime.utcnow(), trigger.nick, trigger, "\n"])
TypeError: sequence item 0: expected string or Unicode, datetime.datetime found

ERROR:sopel.modules.sopel.irc:Exception from #pew: TypeError: sequence item 0: expected string or Unicode, datetime.datetime found (file "/home/paul/.sopel/modules/log.py", line 23, in log_everything) (:pew!~pew@00020d55.user.oftc.net PRIVMSG #pew :asfdj;lkj)
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading log: invalid syntax (log.py, line 23) (loader.py:197)


Registered 1 modules,
1 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading log: invalid syntax (log.py, line 23) (loader.py:197)


Registered 1 modules,
1 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading log: invalid syntax (log.py, line 23) (loader.py:197)


Registered 1 modules,
1 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 2 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 2 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...


Error loading log: expected an indented block (log.py, line 32) (loader.py:197)


Registered 1 modules,
1 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 2 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
Traceback (most recent call last):
  File "/home/paul/workspace/sopel/sopenv/lib/python2.7/site-packages/sopel/bot.py", line 465, in call
    exit_code = func(sopel, trigger)
  File "/home/paul/.sopel/modules/log.py", line 31, in log_everything
    with bot.memory['chanlog_locks'][fpath]:
KeyError: u'chanlog_locks'

ERROR:sopel.modules.sopel.irc:Exception from #pew: KeyError: u'chanlog_locks' (file "/home/paul/.sopel/modules/log.py", line 31, in log_everything) (:pew!~pew@00020d55.user.oftc.net PRIVMSG #pew :;lkjas;d)
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 2 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
Traceback (most recent call last):
  File "/home/paul/workspace/sopel/sopenv/lib/python2.7/site-packages/sopel/bot.py", line 465, in call
    exit_code = func(sopel, trigger)
  File "/home/paul/.sopel/modules/log.py", line 31, in log_everything
    with bot.memory['chanlog_locks'][fpath]:
KeyError: u'chanlog_locks'

ERROR:sopel.modules.sopel.irc:Exception from #pew: KeyError: u'chanlog_locks' (file "/home/paul/.sopel/modules/log.py", line 31, in log_everything) (:pew!~pew@00020d55.user.oftc.net PRIVMSG #pew :sdfg)
KeyboardInterrupt

Welcome to Sopel. Loading modules...




Registered 2 modules,
0 modules failed to load


Connecting to irc.oftc.net:6697...
Connected.
KeyboardInterrupt
